/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from 'ethers'
import { Provider, TransactionRequest } from '@ethersproject/providers'
import type { Random, RandomInterface } from '../Random'

const _abi = [
  {
    inputs: [],
    name: 'PERCENTAGE_THOUSAND',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256'
      }
    ],
    stateMutability: 'view',
    type: 'function'
  }
]

const _bytecode =
  '0x60806040526000805534801561001457600080fd5b5060b4806100236000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c806345b12d4a14602d575b600080fd5b60336047565b604051603e91906065565b60405180910390f35b620186a081565b6000819050919050565b605f81604e565b82525050565b6000602082019050607860008301846058565b9291505056fea264697066735822122048217fc70c6c4cf1701bf451ac250f5fdf7ef41f652edb81252d00de8bdebb7264736f6c63430008090033'

export class Random__factory extends ContractFactory {
  constructor(...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0])
    } else {
      super(...args)
    }
  }

  deploy(overrides?: Overrides & { from?: string | Promise<string> }): Promise<Random> {
    return super.deploy(overrides || {}) as Promise<Random>
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {})
  }
  attach(address: string): Random {
    return super.attach(address) as Random
  }
  connect(signer: Signer): Random__factory {
    return super.connect(signer) as Random__factory
  }
  static readonly bytecode = _bytecode
  static readonly abi = _abi
  static createInterface(): RandomInterface {
    return new utils.Interface(_abi) as RandomInterface
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Random {
    return new Contract(address, _abi, signerOrProvider) as Random
  }
}
